using Immersive.Framework.PlayerParticipation;
using UnityEditor;
using UnityEngine;

namespace Immersive.Framework.Editor.PlayerParticipation
{
    [CustomEditor(typeof(ScenePlayerActorPresentationEvidence))]
    internal sealed class ScenePlayerActorPresentationEvidenceEditor : UnityEditor.Editor
    {
        public override void OnInspectorGUI()
        {
            ScenePlayerActorPresentationEvidence evidence =
                (ScenePlayerActorPresentationEvidence)target;

            EditorGUILayout.HelpBox(
                "Technical provenance generated by Scene-Provided Local Player Apply / Rebuild. Configure the Actor Profile and Scene-Provided Local Player instead of editing this evidence.",
                MessageType.Info);

            using (new EditorGUI.DisabledScope(true))
            {
                EditorGUILayout.ObjectField(
                    "Actor Profile",
                    evidence.ActorProfile,
                    typeof(Immersive.Framework.Actors.ActorProfile),
                    false);
                EditorGUILayout.ObjectField(
                    "Presentation Prefab",
                    evidence.PresentationPrefab,
                    typeof(GameObject),
                    false);
                EditorGUILayout.TextField(
                    "Diagnostic",
                    evidence.AuthoringDiagnostic);
            }
        }
    }
}
