using System;
using System.Collections.Generic;
using Immersive.Framework.ApiStatus;
using Immersive.Framework.Common;
using Immersive.Framework.PlayerSlots;
namespace Immersive.Framework.PlayerParticipation
{
 [FrameworkApiStatus(FrameworkApiStatus.Internal,"P3K.5 gameplay admission aggregation authority.")]
 internal sealed class PlayerGameplayAdmissionRuntimeContext
 {
  private readonly string sessionContextId; private readonly PlayerGameplayOccupancyRuntimeContext occupancyContext; private readonly PlayerGameplayInputBindingRuntimeContext inputContext; private readonly PlayerGameplayCameraEligibilityRuntimeContext cameraContext; private readonly PlayerSlotId[] orderedSlots; private readonly Dictionary<PlayerSlotId,PlayerGameplayAdmissionSummary> slots=new(); private int revision=1,sequence; private PlayerGameplayAdmissionStatus last; private string message="Gameplay admission runtime initialized.";
  private PlayerGameplayAdmissionRuntimeContext(string session,PlayerGameplayOccupancyRuntimeContext occupancy,PlayerGameplayInputBindingRuntimeContext input,PlayerGameplayCameraEligibilityRuntimeContext camera,PlayerSlotId[] ordered){sessionContextId=session;occupancyContext=occupancy;inputContext=input;cameraContext=camera;orderedSlots=ordered;foreach(var s in ordered)slots.Add(s,PlayerGameplayAdmissionSummary.NotAdmitted(session,s,0,nameof(PlayerGameplayAdmissionRuntimeContext),"runtime-initialization","Configured Player Slot is not admitted."));}
  internal string SessionContextId=>sessionContextId; internal int Revision=>revision;
  internal static bool TryCreate(PlayerGameplayOccupancyRuntimeContext occupancy,PlayerGameplayInputBindingRuntimeContext input,PlayerGameplayCameraEligibilityRuntimeContext camera,out PlayerGameplayAdmissionRuntimeContext context,out string issue){context=null;issue=string.Empty;var snapshot=occupancy?.CreateSnapshot();if(snapshot==null||!snapshot.IsInitialized||input==null||camera==null){issue="Gameplay admission requires occupancy, input and camera capability authorities.";return false;}var ordered=new PlayerSlotId[snapshot.ConfiguredSlotCount];for(int i=0;i<ordered.Length;i++)ordered[i]=snapshot.Slots[i].PlayerSlotId;context=new PlayerGameplayAdmissionRuntimeContext(snapshot.SessionContextId,occupancy,input,camera,ordered);return true;}
  internal PlayerGameplayAdmissionResult TryAdmit(PlayerGameplayOccupancySummary occupancy,PlayerGameplayInputBindingSummary input,PlayerGameplayCameraEligibilitySummary camera,string source,string reason)
  { const string op="AdmitGameplay";var slot=occupancy.PlayerSlotId;var previous=Get(slot);if(!Validate(occupancy,input,camera,out var issue)){return Reject(PlayerGameplayAdmissionStatus.RejectedInvalidRequest,op,slot,previous,issue);}if(previous.IsAdmitted&&previous.OccupancyToken==occupancy.Token&&previous.InputBindingToken==input.Token&&previous.CameraEligibilityToken==camera.Token)return Refresh(op,previous,input,source,reason,PlayerGameplayAdmissionStatus.SucceededAlreadyAdmitted,"Gameplay admission is already current.");if(previous.IsAdmitted&&(previous.OccupancyToken!=occupancy.Token||previous.CameraEligibilityToken!=camera.Token))return Reject(PlayerGameplayAdmissionStatus.RejectedSlotAlreadyAdmitted,op,slot,previous,"Player Slot already has another current gameplay admission.");var token=new PlayerGameplayAdmissionToken(sessionContextId,occupancy.Owner,slot,occupancy.ActorProfileId,occupancy.ActorId,occupancy.RuntimeContentIdentity,occupancy.Token.MaterializationRevision,occupancy.OccupancyRevision,input.BindingRevision,camera.CameraRevision,++sequence);var state=input.IsAllowed?PlayerGameplayAdmissionState.Ready:PlayerGameplayAdmissionState.BlockedByInputGate;var current=new PlayerGameplayAdmissionSummary(sessionContextId,slot,state,occupancy.ActorProfileId,occupancy.ActorId,occupancy.Owner,occupancy.RuntimeContentIdentity,occupancy.PreparationToken,occupancy.Token,input.Token,camera.Token,token,token.AdmissionRevision,source,reason,previous.IsAdmitted?"Gameplay admission refreshed for the new Input capability while preserving Camera.":state==PlayerGameplayAdmissionState.Ready?"Gameplay admission aggregated current capabilities.":"Gameplay admission is blocked by the current Input Gate.");slots[slot]=current;revision++;return Result(state==PlayerGameplayAdmissionState.Ready?PlayerGameplayAdmissionStatus.SucceededReady:PlayerGameplayAdmissionStatus.SucceededBlockedByInputGate,op,slot,previous,current,false,false,string.Empty,current.Message); }
  internal PlayerGameplayAdmissionResult TryRefreshReadiness(PlayerSlotId slot,PlayerGameplayAdmissionToken expected,string source,string reason){var previous=Get(slot);if(!previous.IsAdmitted||previous.Token!=expected)return Reject(PlayerGameplayAdmissionStatus.RejectedForeignOrStaleAdmission,"RefreshGameplayReadiness",slot,previous,"Refresh requires the current admission token.");if(!inputContext.TryGetCurrentInputBinding(slot,out var input,out _))return Reject(PlayerGameplayAdmissionStatus.RejectedForeignOrStaleInputBinding,"RefreshGameplayReadiness",slot,previous,"Current Input capability is unavailable.");return Refresh("RefreshGameplayReadiness",previous,input,source,reason,PlayerGameplayAdmissionStatus.SucceededReadinessRefreshed,"Gameplay readiness refreshed.");}
  internal PlayerGameplayAdmissionResult TryRelease(PlayerSlotId slot,PlayerGameplayAdmissionToken expected,string source,string reason){const string op="ReleaseGameplayAdmission";var previous=Get(slot);if(previous.IsNotAdmitted)return expected.IsValid?Reject(PlayerGameplayAdmissionStatus.RejectedForeignOrStaleAdmission,op,slot,previous,"Admission is already released."):Result(PlayerGameplayAdmissionStatus.SucceededAlreadyReleased,op,slot,previous,previous,false,false,string.Empty,"Admission is already released.");if(previous.Token!=expected)return Reject(PlayerGameplayAdmissionStatus.RejectedForeignOrStaleAdmission,op,slot,previous,"Release requires the exact admission token.");var current=PlayerGameplayAdmissionSummary.NotAdmitted(sessionContextId,slot,previous.AdmissionRevision,source,reason,"Gameplay admission released; camera, input and occupancy remain owned by their capabilities.");slots[slot]=current;revision++;return Result(PlayerGameplayAdmissionStatus.SucceededReleased,op,slot,previous,current,false,false,string.Empty,current.Message);}
  internal bool TryReleaseAll(string source,string reason,out int released,out int failed,out string issue){released=0;failed=0;var errors=new List<string>();foreach(var slot in orderedSlots){var current=Get(slot);if(!current.IsAdmitted)continue;var r=TryRelease(slot,current.Token,source,reason);if(r.Succeeded)released++;else{failed++;errors.Add(r.ToDiagnosticString());}}issue=string.Join(" | ",errors);return failed==0;}
  internal PlayerGameplayAdmissionSnapshot CreateSnapshot(){var ordered=new PlayerGameplayAdmissionSummary[orderedSlots.Length];for(int i=0;i<ordered.Length;i++)ordered[i]=slots[orderedSlots[i]];return new PlayerGameplayAdmissionSnapshot(sessionContextId,revision,ordered,last,message);}
  private bool Validate(PlayerGameplayOccupancySummary occupancy,PlayerGameplayInputBindingSummary input,PlayerGameplayCameraEligibilitySummary camera,out string issue){issue=string.Empty;if(!occupancy.IsOccupied||!input.IsBound||!camera.HasCurrentDecision||!camera.IsValid){issue="Admission requires current occupancy, input and camera capabilities.";return false;}if(occupancy.PlayerSlotId!=input.PlayerSlotId||occupancy.PlayerSlotId!=camera.PlayerSlotId||occupancy.PreparationToken!=input.PreparationToken||occupancy.PreparationToken!=camera.PreparationToken){issue="Capabilities do not describe the same prepared Player.";return false;}if(!occupancyContext.TryGetSummary(occupancy.PlayerSlotId,out var currentOccupancy)||currentOccupancy.Token!=occupancy.Token||!inputContext.TryGetCurrentInputBinding(occupancy.PlayerSlotId,out var currentInput,out _)||currentInput.Token!=input.Token||!cameraContext.CreateSnapshot().TryGetSummary(occupancy.PlayerSlotId,out var currentCamera)||currentCamera.Token!=camera.Token){issue="One or more supplied capabilities are stale.";return false;}return true;}
  private PlayerGameplayAdmissionResult Refresh(string op,PlayerGameplayAdmissionSummary previous,PlayerGameplayInputBindingSummary input,string source,string reason,PlayerGameplayAdmissionStatus status,string text){var state=input.IsAllowed?PlayerGameplayAdmissionState.Ready:PlayerGameplayAdmissionState.BlockedByInputGate;var current=new PlayerGameplayAdmissionSummary(previous.SessionContextId,previous.PlayerSlotId,state,previous.ActorProfileId,previous.ActorId,previous.Owner,previous.RuntimeContentIdentity,previous.PreparationToken,previous.OccupancyToken,previous.InputBindingToken,previous.CameraEligibilityToken,previous.Token,previous.AdmissionRevision,source,reason,text);slots[previous.PlayerSlotId]=current;return Result(status,op,previous.PlayerSlotId,previous,current,false,false,string.Empty,text);}
  private PlayerGameplayAdmissionSummary Get(PlayerSlotId slot)=>slot.IsValid&&slots.TryGetValue(slot,out var value)?value:default;
  private PlayerGameplayAdmissionResult Reject(PlayerGameplayAdmissionStatus status,string op,PlayerSlotId slot,PlayerGameplayAdmissionSummary current,string text)=>Result(status,op,slot,current,current,false,false,string.Empty,text);
  private PlayerGameplayAdmissionResult Result(PlayerGameplayAdmissionStatus status,string op,PlayerSlotId slot,PlayerGameplayAdmissionSummary previous,PlayerGameplayAdmissionSummary current,bool rollback,bool rolled,string rollbackIssue,string text){last=status;message=text.NormalizeText();return new PlayerGameplayAdmissionResult(status,op,slot,previous,current,CreateSnapshot(),rollback,rolled,rollbackIssue,message);}
 }
}
