using System;
using System.Collections.Generic;
using Immersive.Framework.ApiStatus;
using Immersive.Framework.Common;
using Immersive.Framework.PlayerSlots;
using Immersive.Framework.RuntimeContent;
namespace Immersive.Framework.PlayerParticipation
{
 [FrameworkApiStatus(FrameworkApiStatus.Internal,"P3K.5 gameplay admission aggregation authority.")]
 internal sealed class PlayerGameplayAdmissionRuntimeContext
 {
  private readonly string _sessionContextId; private readonly PlayerGameplayOccupancyRuntimeContext _occupancyContext; private readonly PlayerGameplayInputBindingRuntimeContext _inputContext; private readonly PlayerGameplayCameraEligibilityRuntimeContext _cameraContext; private readonly PlayerSlotId[] _orderedSlots; private readonly Dictionary<PlayerSlotId,PlayerGameplayAdmissionSummary> _slots=new(); private int _revision=1,_sequence; private PlayerGameplayAdmissionStatus _last; private string _message="Gameplay admission runtime initialized.";
  private PlayerGameplayAdmissionRuntimeContext(string session,PlayerGameplayOccupancyRuntimeContext occupancy,PlayerGameplayInputBindingRuntimeContext input,PlayerGameplayCameraEligibilityRuntimeContext camera,PlayerSlotId[] ordered){_sessionContextId=session;_occupancyContext=occupancy;_inputContext=input;_cameraContext=camera;_orderedSlots=ordered;foreach(var s in ordered)_slots.Add(s,PlayerGameplayAdmissionSummary.NotAdmitted(session,s,0,nameof(PlayerGameplayAdmissionRuntimeContext),"runtime-initialization","Configured Player Slot is not admitted."));}
  internal string SessionContextId=>_sessionContextId; internal int Revision=>_revision;
  internal static bool TryCreate(PlayerGameplayOccupancyRuntimeContext occupancy,PlayerGameplayInputBindingRuntimeContext input,PlayerGameplayCameraEligibilityRuntimeContext camera,out PlayerGameplayAdmissionRuntimeContext context,out string issue){context=null;issue=string.Empty;var snapshot=occupancy?.CreateSnapshot();if(snapshot==null||!snapshot.IsInitialized||input==null||camera==null){issue="Gameplay admission requires occupancy, input and camera capability authorities.";return false;}var ordered=new PlayerSlotId[snapshot.ConfiguredSlotCount];for(int i=0;i<ordered.Length;i++)ordered[i]=snapshot.Slots[i].PlayerSlotId;context=new PlayerGameplayAdmissionRuntimeContext(snapshot.SessionContextId,occupancy,input,camera,ordered);return true;}
  internal PlayerGameplayAdmissionResult TryAdmit(RuntimeContentOwner contextualOwner,PlayerGameplayOccupancySummary occupancy,PlayerGameplayInputBindingSummary input,PlayerGameplayCameraEligibilitySummary camera,string source,string reason)
  { const string op="AdmitGameplay";var slot=occupancy.PlayerSlotId;var previous=Get(slot);if(!contextualOwner.IsValid||contextualOwner.Scope!=RuntimeContentScope.Activity)return Reject(PlayerGameplayAdmissionStatus.RejectedInvalidRequest,op,slot,previous,"Gameplay admission requires a valid Activity contextual owner.");if(!Validate(contextualOwner,occupancy,input,camera,out string issue))return Reject(PlayerGameplayAdmissionStatus.RejectedInvalidRequest,op,slot,previous,issue);if(previous.IsAdmitted&&previous.Owner==contextualOwner&&previous.OccupancyToken==occupancy.Token&&previous.InputBindingToken==input.Token&&previous.CameraEligibilityToken==camera.Token)return Refresh(op,previous,input,source,reason,PlayerGameplayAdmissionStatus.SucceededAlreadyAdmitted,"Gameplay admission is already current.");if(previous.IsAdmitted)return Reject(PlayerGameplayAdmissionStatus.RejectedSlotAlreadyAdmitted,op,slot,previous,"Player Slot already has another current gameplay admission.");var token=new PlayerGameplayAdmissionToken(_sessionContextId,contextualOwner,slot,occupancy.ActorProfileId,occupancy.ActorId,occupancy.RuntimeContentIdentity,occupancy.Token.MaterializationRevision,occupancy.OccupancyRevision,input.BindingRevision,camera.CameraRevision,++_sequence);var state=input.IsAllowed?PlayerGameplayAdmissionState.Ready:PlayerGameplayAdmissionState.BlockedByInputGate;var current=new PlayerGameplayAdmissionSummary(_sessionContextId,slot,state,occupancy.ActorProfileId,occupancy.ActorId,contextualOwner,occupancy.RuntimeContentIdentity,occupancy.PreparationToken,occupancy.Token,input.Token,camera.Token,token,token.AdmissionRevision,source,reason,state==PlayerGameplayAdmissionState.Ready?"Gameplay admission aggregated current contextual capabilities.":"Gameplay admission is blocked by the current Input Gate.");_slots[slot]=current;_revision++;return Result(state==PlayerGameplayAdmissionState.Ready?PlayerGameplayAdmissionStatus.SucceededReady:PlayerGameplayAdmissionStatus.SucceededBlockedByInputGate,op,slot,previous,current,false,false,string.Empty,current.Message); }
  internal PlayerGameplayAdmissionResult TryRefreshReadiness(PlayerSlotId slot,PlayerGameplayAdmissionToken expected,string source,string reason){var previous=Get(slot);if(!previous.IsAdmitted||previous.Token!=expected)return Reject(PlayerGameplayAdmissionStatus.RejectedForeignOrStaleAdmission,"RefreshGameplayReadiness",slot,previous,"Refresh requires the current admission token.");if(!_inputContext.TryGetCurrentInputBinding(slot,out var input,out _))return Reject(PlayerGameplayAdmissionStatus.RejectedForeignOrStaleInputBinding,"RefreshGameplayReadiness",slot,previous,"Current Input capability is unavailable.");if(input.Owner!=previous.Owner||input.Token.Owner!=previous.Owner)return Reject(PlayerGameplayAdmissionStatus.RejectedForeignOrStaleInputBinding,"RefreshGameplayReadiness",slot,previous,"Current Input capability belongs to another Activity occurrence.");return Refresh("RefreshGameplayReadiness",previous,input,source,reason,PlayerGameplayAdmissionStatus.SucceededReadinessRefreshed,"Gameplay readiness refreshed.");}
  internal PlayerGameplayAdmissionResult TryRelease(PlayerSlotId slot,PlayerGameplayAdmissionToken expected,string source,string reason){const string op="ReleaseGameplayAdmission";var previous=Get(slot);if(previous.IsNotAdmitted)return expected.IsValid?Reject(PlayerGameplayAdmissionStatus.RejectedForeignOrStaleAdmission,op,slot,previous,"Admission is already released."):Result(PlayerGameplayAdmissionStatus.SucceededAlreadyReleased,op,slot,previous,previous,false,false,string.Empty,"Admission is already released.");if(previous.Token!=expected)return Reject(PlayerGameplayAdmissionStatus.RejectedForeignOrStaleAdmission,op,slot,previous,"Release requires the exact admission token.");var current=PlayerGameplayAdmissionSummary.NotAdmitted(_sessionContextId,slot,previous.AdmissionRevision,source,reason,"Gameplay admission released; camera, input and occupancy remain owned by their capabilities.");_slots[slot]=current;_revision++;return Result(PlayerGameplayAdmissionStatus.SucceededReleased,op,slot,previous,current,false,false,string.Empty,current.Message);}
  internal bool TryReleaseAll(string source,string reason,out int released,out int failed,out string issue){released=0;failed=0;var errors=new List<string>();foreach(var slot in _orderedSlots){var current=Get(slot);if(!current.IsAdmitted)continue;var r=TryRelease(slot,current.Token,source,reason);if(r.Succeeded)released++;else{failed++;errors.Add(r.ToDiagnosticString());}}issue=string.Join(" | ",errors);return failed==0;}
  internal PlayerGameplayAdmissionSnapshot CreateSnapshot(){var ordered=new PlayerGameplayAdmissionSummary[_orderedSlots.Length];for(int i=0;i<ordered.Length;i++)ordered[i]=_slots[_orderedSlots[i]];return new PlayerGameplayAdmissionSnapshot(_sessionContextId,_revision,ordered,_last,_message);}
  private bool Validate(RuntimeContentOwner contextualOwner,PlayerGameplayOccupancySummary occupancy,PlayerGameplayInputBindingSummary input,PlayerGameplayCameraEligibilitySummary camera,out string issue){issue=string.Empty;if(!occupancy.IsOccupied||!input.IsBound||!camera.HasCurrentDecision||!camera.IsValid){issue="Admission requires current occupancy, input and camera capabilities.";return false;}if(input.Owner!=contextualOwner||input.Token.Owner!=contextualOwner){issue="Gameplay input binding does not belong to the current Activity occurrence.";return false;}if(occupancy.PlayerSlotId!=input.PlayerSlotId||occupancy.PlayerSlotId!=camera.PlayerSlotId||occupancy.PreparationToken!=input.PreparationToken||occupancy.PreparationToken!=camera.PreparationToken){issue="Capabilities do not describe the same prepared Player.";return false;}if(!_occupancyContext.TryGetSummary(occupancy.PlayerSlotId,out var currentOccupancy)||currentOccupancy.Token!=occupancy.Token||!_inputContext.TryGetCurrentInputBinding(occupancy.PlayerSlotId,out var currentInput,out _)||currentInput.Token!=input.Token||!_cameraContext.CreateSnapshot().TryGetSummary(occupancy.PlayerSlotId,out var currentCamera)||currentCamera.Token!=camera.Token){issue="One or more supplied capabilities are stale.";return false;}return true;}
  private PlayerGameplayAdmissionResult Refresh(string op,PlayerGameplayAdmissionSummary previous,PlayerGameplayInputBindingSummary input,string source,string reason,PlayerGameplayAdmissionStatus status,string text){var state=input.IsAllowed?PlayerGameplayAdmissionState.Ready:PlayerGameplayAdmissionState.BlockedByInputGate;var current=new PlayerGameplayAdmissionSummary(previous.SessionContextId,previous.PlayerSlotId,state,previous.ActorProfileId,previous.ActorId,previous.Owner,previous.RuntimeContentIdentity,previous.PreparationToken,previous.OccupancyToken,previous.InputBindingToken,previous.CameraEligibilityToken,previous.Token,previous.AdmissionRevision,source,reason,text);_slots[previous.PlayerSlotId]=current;return Result(status,op,previous.PlayerSlotId,previous,current,false,false,string.Empty,text);}
  private PlayerGameplayAdmissionSummary Get(PlayerSlotId slot)=>slot.IsValid&&_slots.TryGetValue(slot,out var value)?value:default;
  private PlayerGameplayAdmissionResult Reject(PlayerGameplayAdmissionStatus status,string op,PlayerSlotId slot,PlayerGameplayAdmissionSummary current,string text)=>Result(status,op,slot,current,current,false,false,string.Empty,text);
  private PlayerGameplayAdmissionResult Result(PlayerGameplayAdmissionStatus status,string op,PlayerSlotId slot,PlayerGameplayAdmissionSummary previous,PlayerGameplayAdmissionSummary current,bool rollback,bool rolled,string rollbackIssue,string text){_last=status;_message=text.NormalizeText();return new PlayerGameplayAdmissionResult(status,op,slot,previous,current,CreateSnapshot(),rollback,rolled,rollbackIssue,_message);}
 }
}
